# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstone_app', '0004_auto_20170121_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_agree',
            fields=[
                ('agid', models.AutoField(primary_key=True, serialize=False)),
                ('answer_id', models.IntegerField(default=0)),
                ('agree_user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
