# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstone_app', '0005_answer_agree'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer_agree',
            new_name='Agree_answer',
        ),
    ]
